package com.mingda.common.ibatis.data;

import java.math.BigDecimal;
import java.util.Date;

public class SysTInfolog {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.INFOLOG_ID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private BigDecimal infologId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.EMPLOYEE_ID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private BigDecimal employeeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.LOGTIME
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private Date logtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.FAMILYID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private BigDecimal familyid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.CODE
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.ENTITYID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private BigDecimal entityid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUMMER.SYS_T_INFOLOG.LOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    private String log;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.INFOLOG_ID
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.INFOLOG_ID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public BigDecimal getInfologId() {
        return infologId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.INFOLOG_ID
     *
     * @param infologId the value for SUMMER.SYS_T_INFOLOG.INFOLOG_ID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setInfologId(BigDecimal infologId) {
        this.infologId = infologId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.EMPLOYEE_ID
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.EMPLOYEE_ID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public BigDecimal getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.EMPLOYEE_ID
     *
     * @param employeeId the value for SUMMER.SYS_T_INFOLOG.EMPLOYEE_ID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setEmployeeId(BigDecimal employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.LOGTIME
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.LOGTIME
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.LOGTIME
     *
     * @param logtime the value for SUMMER.SYS_T_INFOLOG.LOGTIME
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.FAMILYID
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.FAMILYID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public BigDecimal getFamilyid() {
        return familyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.FAMILYID
     *
     * @param familyid the value for SUMMER.SYS_T_INFOLOG.FAMILYID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setFamilyid(BigDecimal familyid) {
        this.familyid = familyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.CODE
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.CODE
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.CODE
     *
     * @param code the value for SUMMER.SYS_T_INFOLOG.CODE
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.ENTITYID
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.ENTITYID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public BigDecimal getEntityid() {
        return entityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.ENTITYID
     *
     * @param entityid the value for SUMMER.SYS_T_INFOLOG.ENTITYID
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setEntityid(BigDecimal entityid) {
        this.entityid = entityid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUMMER.SYS_T_INFOLOG.LOG
     *
     * @return the value of SUMMER.SYS_T_INFOLOG.LOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUMMER.SYS_T_INFOLOG.LOG
     *
     * @param log the value for SUMMER.SYS_T_INFOLOG.LOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    public void setLog(String log) {
        this.log = log;
    }
}