/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system.unit;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;
import com.mingda.common.log4j.Log4jApp;

/**
 * MyEclipse Struts Creation date: 09-09-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class CheckunitAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			request.setCharacterEncoding("utf-8");
		} catch (UnsupportedEncodingException e1) {
			e1.printStackTrace();
		}
		Session session = SessionFactory.getSession();
		Connection conn = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		String unitname = "";
		String sql = "";
		String result = "";
		try {
			conn = session.connection();
			unitname = request.getParameter("unitname");
			if(null==unitname||"".equals("unitname")){
				
			} else {
				unitname = unitname.trim();
			}
			sql = "select * from sys_t_unit u ";
			sql = sql + " where  u.unitname ='" + unitname + "'";
			pstmt = conn.prepareStatement(sql);
			Log4jApp.logger("工作单位:" + sql);
			rs = pstmt.executeQuery();
			if (rs.next()) {
				result = "1";
			} else {
				result = "0";
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		response.setContentType("text/html");
		response.setCharacterEncoding("GB18030");

		try {
			PrintWriter out = response.getWriter();
			out.println(result);
			out.flush();
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return null;
	}
}