/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.card;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;

/**
 * MyEclipse Struts Creation date: 06-23-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class GetMemberPicAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings({ "unused", "deprecation" })
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("text/html");
		response.setCharacterEncoding("GB18030");

		String nodeName = request.getParameter("nodeName");
		String nodeId = request.getParameter("nodeId");
		Session session = SessionFactory.getSession();
		String sql = "select inchurl from info_t_member t where t.member_id='"
				+ nodeId + "'";
		//log.debug(sql);
		String url = "";
		try {
			Connection conn = session.connection();
			PreparedStatement ps = conn.prepareStatement(sql);
			ResultSet rs = ps.executeQuery();
			if (rs.next()) {
				url = rs.getString("inchurl");
			}
			//log.debug(url);
			if (url == null || url.equals("")) {
				url = "<br/><img id=\"mpicc\" src=\"../../images/nopic.gif\" width=\"70\" height=\"91\" />";
			} else {
				// <img src="<%="http://"+
				// request.getServerName()+":"+request.getServerPort()+"/a"+"/inch/"+masterId+"/"+masterId+".jpg"
				// %>" width="70" height="91" />
				url = "<br/><img  id=\"mpicc\" src=\"http://" + request.getServerName() + ":"
						+ request.getServerPort() + "/upload/" + url
						+ "\" width=\"70\" height=\"91\" />";
			}
			PrintWriter out = response.getWriter();
			out
					.println(url);
			out.flush();
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}
}