/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.card;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;

import com.mingda.common.node.TreeHandle;
import com.mingda.common.node.TreeHandleImpl;
import com.mingda.common.page.PageView;

/**
 * MyEclipse Struts Creation date: 06-21-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class MemberInfoCardLeafAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String code = request.getParameter("code");
		String codeId = request.getParameter("codeId");
		String cols = request.getParameter("cols");
		Document dictionary = (Document) this.servlet.getServletContext()
				.getAttribute("dictionary");
		
		Document treedoc = (Document) servlet.getServletContext()
		.getAttribute("tree");
		TreeHandle tree = new TreeHandleImpl(treedoc);
		
		PageView pv = new PageView();
		Document doc = tree.selectSingleEntity(code, new Long(codeId));
		try {
			doc = pv
					.writeTablebyXML(doc, dictionary, new Long(cols).intValue());
			PrintWriter out = response.getWriter();
			response.setCharacterEncoding("GB18030");
			response.setContentType("text/html");
			out.write(doc.getRootElement().asXML());
			out.flush();
			out.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}
}