/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.oa;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTOrganizationDAO;
import com.mingda.entity.SysTOrganization;

/**
 * MyEclipse Struts Creation date: 12-30-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class GetChildsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			String orgid = request.getParameter("orgid");
			if (null != orgid && !"".equals(orgid)) {
				int l = orgid.length() / 2 + 1;
				response.setCharacterEncoding("gb18030");
				SysTOrganizationDAO organdao = new SysTOrganizationDAO();
				List<SysTOrganization> list = organdao.findByParentorgid(orgid);
				String html = "";
				if (null!=list&&0<list.size()) {
					html = "<span id =\"zone"
							+ l
							+ "\">>>><select name=\"sel\" onchange=\"selPerson(this)\"><option value=\"\">Î´Ñ¡Ôñ...</option>";
					for (SysTOrganization sysTOrganization : list) {
						html += "<option value=\""
								+ sysTOrganization.getOrganizationId() + "\">"
								+ sysTOrganization.getOrgname() + "</option>";
					}
					html += "</select></span>";
				}
				PrintWriter out = response.getWriter();
				out.println(html);
				out.close();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}finally{
			SessionFactory.closeSession();
		}
		return null;
	}
}