/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.oa;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.dao.NetTFileDAO;
import com.mingda.entity.NetTFile;

/**
 * MyEclipse Struts Creation date: 12-25-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class OafileviewAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String fileid = request.getParameter("fileid");
		response.setCharacterEncoding("GB18030");
		NetTFileDAO dao = new NetTFileDAO();
		NetTFile netfile = dao.findById(new Long(fileid));

		FileUpload fu = new FileUpload();
		String path = fu.isFileExists();
		String filename= netfile.getFilename();
		filename= filename.substring(filename.lastIndexOf("-")+1, filename.length());
		OutputStream os;
		try {
			os = response.getOutputStream();
			response.reset();
			response.setContentType("APPLICATION/OCTET-STREAM");
			response.setHeader("Content-Disposition", "attachment; filename=\""
					+new String (filename.getBytes(),"iso-8859-1") + "\"");
			String temp = netfile.getFilepath();
			File file = new File(temp);
			InputStream in = new java.io.FileInputStream(file);
			byte[] b = new byte[2048];
			int len;
			while ((len = in.read(b)) > 0) {
				response.getOutputStream().write(b, 0, len);
			}
			in.close();
			os.close();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return null;
	}
}