/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.oa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.Pager;
import com.mingda.common.SessionFactory;
import com.mingda.common.log4j.Log4jApp;
import com.mingda.entity.SysTEmployee;

/** 
 * MyEclipse Struts
 * Creation date: 12-31-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class TransferrecequeryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession hsession = request.getSession();
		Session session = SessionFactory.getSession();
		Connection conn = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		String curpage = request.getParameter("cur_page");
		String btime = "";
		String etime = "";
		String sql = "";
		try {
			conn = session.connection();
			int totalrow = 0;
			Pager page = null;
			if (curpage == null || curpage.equals("")) {
				btime = request.getParameter("btime");
				etime = request.getParameter("etime");
				SysTEmployee employee = (SysTEmployee) hsession
						.getAttribute("employee");
				sql = "select t.*, "
						+ " (select e.name from sys_t_empext e where e.employee_id = t.owner) as ownername,"
						+ " (select e.name from sys_t_empext e where e.employee_id = t.receiver) as recename"
						+ "  from net_t_transfer t" + " where t.receiver = '"
						+ employee.getEmployeeId() + "' ";
				if ("".equals(btime) || "".equals(etime) || null == btime
						|| null == etime) {
				} else {
					sql = sql + " and t.transfertime between to_date('" + btime
							+ "', 'yyyy-mm-dd') and" + " to_date('" + etime
							+ "', 'yyyy-mm-dd') ";
				}
				sql = sql + "  order by t.transfertime desc";
				Log4jApp.logger("通知sql:" + sql);
				pstmt = conn.prepareStatement("select count(1) from ( " + sql
						+ " )");
				hsession.setAttribute("sql", sql);
				rs = pstmt.executeQuery();
				if (rs.next()) {
					totalrow = rs.getInt(1);
				}
				page = new Pager(totalrow, new Long(1).intValue(), "0");
				pstmt = conn
						.prepareStatement("select * from (select mytab.*, rownum row_num from ("
								+ sql
								+ ") mytab) where row_num between "
								+ page.getBeiginrow()
								+ " and "
								+ page.getEndrow());
				rs = pstmt.executeQuery();
			} else {
				sql = (String) hsession.getAttribute("sql");
				pstmt = conn.prepareStatement("select count(1) from ( " + sql
						+ " )");
				rs = pstmt.executeQuery();
				if (rs.next()) {
					totalrow = rs.getInt(1);
				}
				page = new Pager(totalrow, new Long(curpage).intValue(), "0");
				pstmt = conn
						.prepareStatement("select * from (select mytab.*, rownum row_num from ("
								+ sql
								+ ") mytab) where row_num between "
								+ page.getBeiginrow()
								+ " and "
								+ page.getEndrow());
				rs = pstmt.executeQuery();
			}
			page.setUrl("transferrecequery.do");
			String html = "";
			while (rs.next()) {
				html += "<tr><td>"
						+ rs.getString("title")
						+ "</td><td>"
						+ rs.getString("ownername")
						+ "</td><td>"
						+ rs.getString("recename")
						+ "</td><td>"
						+ rs.getString("transfertime")
						+ "</td><td><a href=\"transferbrowser.do?reltable=NET_T_TRANSFER&relid="
						+ rs.getString("transfer_id")
						+ "\" target=\"_blank\">查看</a>"
						+ "" + "</td></tr>";
			}
			request.setAttribute("html", html);
			request.setAttribute("toolsmenu", page.getToolsMenu());
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			try {
				if (rs != null) {
					rs.close();
				}
				if (pstmt != null) {
					pstmt.close();
				}
				if (conn != null) {
					conn.close();
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
			session.close();

		}

		return mapping.findForward("transferrecequery");
	}
}