/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.oa;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;
import com.mingda.dao.NetTNoticeDAO;
import com.mingda.entity.NetTNotice;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 12-27-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="welcome" path="/page/welcome.jsp"
 */
public class WelcomeAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		Session session = SessionFactory.getSession();

		HttpSession hsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) hsession
				.getAttribute("employee");
		String orgid = employee.getSysTOrganization().getOrganizationId();
		// 读取通知和公告
		String notciehtml = "";
		NetTNoticeDAO noticedao = new NetTNoticeDAO();
		List<NetTNotice> notices = noticedao.findNoticeClient(orgid);
		if (null != notices && notices.size() > 0) {
			int j = notices.size();
			if (j > 6) {
				j = 6;
			}
			for (int i = 0; i < j; i++) {
				String a = "";
				String type = "";
				NetTNotice notice = notices.get(i);
				if ("1".equals(notice.getNoticetype().toString())) {
					a = "oa/noticebrowser.do?reltable=NET_T_NOTICE&relid="
							+ notice.getNoticeId() + "";
					type = "通知";
				} else {
					a = "oa/announcmentbrowser.do?reltable=NET_T_NOTICE&relid="
							+ notice.getNoticeId() + "";
					type = "公告";
				}
				String title = notice.getTitle();
				title = this.editorTitle(title);
				notciehtml = notciehtml
						+ "<tr height=\"19\"><td class=\"content\"><a href=\""
						+ a
						+ "\" target=\"_blank\"><span style=\"width:150px\">"
						+ type
						+ "&nbsp;&nbsp;"
						+ notice.getAuthor()
						+ ":</span><span title=\""
						+ notice.getTitle()
						+ "\" style=\"width:200px;text-align:left\">"
						+ title
						+ "</span>&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"width:150px;text-align:right\">"
						+ notice.getIssuetime() + "</span></a></td></tr>";
			}
			if (j < 6) {
				for (int m = 0; m < 6 - j; m++) {
					notciehtml = notciehtml
							+ "<tr height=\"19\"><td class=\"content\"></td><td>&nbsp;<td></tr>";
				}
			}
			request.setAttribute("notciehtml", notciehtml);
		}
		// 读取通知和公告

		// 代办事宜

		// 信息不合法数据
		String infohtml = "";
		int ROWS = 13;
		String sql = "select term.name, t.* ,f.familyno ,f.mastername ,o.fullname from  biz_t_validateterm term ,biz_t_validatelog t, info_t_family f ,sys_t_organization o"
				+ " where f.family_id=t.family_id  and term.validateterm_id =t.validateterm_id and o.organization_id =f.organization_id and f.organization_id like '"
				+ orgid + "%' ";
		Query q = session.createSQLQuery(sql);
		List infos = q.list();
		if (null != infos && infos.size() > 0) {
			int j = infos.size();
			if (j > ROWS) {
				j = ROWS;
			}
			for (int i = 0; i < j; i++) {
				Object[] objs = (Object[]) infos.get(i);
				infohtml = infohtml
						+ "<tr><td height=\"20\" width=\"150\" class=\"content\"><a href=\"../page/info/card/newfamilyinfocard.do?entityId="
						+ objs[6] + "\" target=\"_blank\">" + objs[7]
						+ "</a></td><td width=\"150\">" + objs[8] + "</td><td>"
						+ objs[0] + "</td></tr>";
			}
			if (j < ROWS) {
				for (int m = 0; m < ROWS - j; m++) {
					infohtml = infohtml
							+ "<tr height=\"19\"><td width=\"150\"  height=\"20\" class=\"content\">&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>";
				}
			}
		}
		request.setAttribute("infohtml", infohtml);
		session.close();
		return mapping.findForward("welcome");
	}

	public String editorTitle(String title) {
		if (null == title || "".equals(title)) {
			title = "无";
		} else {
			if (title.length() > 10) {
				title = title.substring(0, 10) + "...";
			} else {
			}
		}
		return title;
	}
}