/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.editor;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;

import com.mingda.common.node.TreeHandle;
import com.mingda.common.node.TreeHandleImpl;
import com.mingda.common.page.PageView;

/**
 * MyEclipse Struts Creation date: 06-21-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class InfoFormInitAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String code = request.getParameter("code");
		String entityId = request.getParameter("entityId");

		Document treedoc = (Document) servlet.getServletContext().getAttribute(
				"tree");
		TreeHandle th = new TreeHandleImpl(treedoc);

		Document entity = th.selectSingleEntity(code, new Long(entityId));
		Document dictionary = (Document) servlet.getServletContext()
				.getAttribute("dictionary");
		PageView pv = new PageView();// writeFormbyXML();
		Document doc = pv.writeFormbyXML(entity, dictionary, 1);
		request.setAttribute("formdoc", doc.getRootElement().asXML());
		return mapping.findForward("infoeditor");
	}
}