/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.move;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.log4j.Log4jApp;
import com.mingda.entity.SysTEmployee;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MoveexternaloutAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	static Logger logger =Logger.getLogger(MoveexternaloutAction.class);
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		logger.debug("迁出");
		String result="迁出成功";
		Session session = SessionFactory.getSession();
		HttpSession hsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) hsession
				.getAttribute("employee");
		String familyId = request.getParameter("familyId");
		String orgid = request.getParameter("orgid");
		String county = request.getParameter("county");
		String famno = request.getParameter("famno");
		Transaction tx = session.beginTransaction();
		Connection con = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		String sql = "";
		try {
			con =session.connection();
			sql = "update info_t_family set status='2' where family_id = '" + familyId + "'";
			Log4jApp.logger("更新家庭："+sql);
			ps = con.prepareStatement(sql);
			ps.execute();
			sql = "insert into biz_t_familymove (familymove_id, family_id, ofamilyno, oorgid, noptperson ,nopttime, nfamilyno, norgid, ooptperson, oopttime, isover) values "
					+ "(xfamilymove_id.nextval, '"
					+ familyId
					+ "','"
					+ famno
					+ "', '"
					+ orgid
					+ "', '', '', '', '"
					+ county
					+ "', '"
					+ employee.getEmployeeId() + "',sysdate, '0')";
			logger.debug("插入区内迁出记录："+sql);
			ps = con.prepareStatement(sql);
			ps.execute();
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
			e.printStackTrace();
			result="迁移失败";
		} finally {
			try {
				if (rs != null) {
					rs.close();
				}
				if (ps != null) {
					ps.close();
				}
				if (con != null) {
					con.close();
				}
				session.close();
			} catch (SQLException e) {
				result="迁移失败";
				e.printStackTrace();
			}
		}
		response.setContentType("text/html");
		response.setCharacterEncoding("GB18030");

		try {
			PrintWriter out = response.getWriter();
			out.write("<script>alert('"+result+"');");
			out.write("parent.frames['query'].location.reload(parent.frames['query'].location.href);</script>");
			out.flush();
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		logger.debug("迁出");
		return null;
	}
}