/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.move;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.log4j.Log4jApp;

/**
 * MyEclipse Struts Creation date: 08-25-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class MoveexternaloutinitAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String nodeId = request.getParameter("nodeId");
		Session session = SessionFactory.getSession();
		Connection con = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		String sql = "";
		String oldOrgId = "";
		String html = "<input name=\"familyId\" type=\"hidden\" value=\""
				+ nodeId
				+ "\" />"
				+ "<table width=\"100%\" border=\"0\" cellspacing=\"4\" cellpadding=\"0\">";
		Transaction tx = session.beginTransaction();
		try {
			con = session.connection();
			/**
			 * 验证是否可以进行迁移 证件 业务 判断
			 */
			// sql = " select  *  from biz_t_optcheck t where  t.family_id='"
			// + nodeId + "'";
			// Log4jApp.logger(sql);
			// ps = con.prepareStatement(sql);
			// rs = ps.executeQuery();
			boolean flag = false;
			// while (rs.next()) {
			// flag = true;
			// }
			if (flag) {
				request.setAttribute("result", "请撤销所有业务，在进行迁出!");
			} else {
				sql = "select fam.*,org.orgname,org.fullname "
						+ " from info_t_family fam, sys_t_organization org "
						+ "where fam.family_id = '" + nodeId + "' "
						+ " and org.organization_id = fam.organization_id";
				Log4jApp.logger(sql);
				ps = con.prepareStatement(sql);
				rs = ps.executeQuery();
				if (rs.next()) {
					oldOrgId = rs.getString("organization_id");
					String registeredaddress = rs.getString("RPRADDRESS");
					if (registeredaddress == null
							|| registeredaddress.equals("")
							|| registeredaddress.equals("null")) {
						registeredaddress = rs.getString("fullname");
					}
					String familyaddress = rs.getString("FAMADDRESS");
					if (familyaddress == null || familyaddress.equals("")
							|| familyaddress.equals("null")) {
						familyaddress = rs.getString("fullname");
					}
					html += "<input name=\"orgid\" type=\"hidden\" value=\""
							+ oldOrgId + "\" />";
					html += "<input name=\"famno\" type=\"hidden\" value=\""
							+ rs.getString("familyno") + "\" />";
					html += "<tr valign=\"middle\"><td width=\"80\" height=\"25\">家庭编号</td><td>"
							+ rs.getString("familyno") + " </td></tr>";
					html += "<tr valign=\"middle\"><td width=\"80\" height=\"25\">户主姓名</td><td>"
							+ rs.getString("mastername") + "</td></tr>";
					// html +=
					// "<tr valign=\"middle\"><td width=\"80\" height=\"25\">户口地址</td><td><input name=\"registeredaddress\" size=\"80\" type=\"text\" value=\""
					// + registeredaddress + "\" /></td></tr>";
					// html +=
					// "<tr valign=\"middle\"><td width=\"80\" height=\"25\">居住地址</td><td><input name=\"familyaddress\" size=\"80\" type=\"text\" value=\""
					// + familyaddress + "\" /></td></tr>";
				}
				sql = "select * from sys_t_organization org where org.parentorgid = substr('"
						+ oldOrgId + "', 1, 2) order by org.organization_id";
				ps = con.prepareStatement(sql);
				rs = ps.executeQuery();
				String city = "";
				while (rs.next()) {

					if (rs.getString("organization_id").equals(
							oldOrgId.substring(0, 4))) {
						city += "<option selected=\"selected\" value=\""
								+ rs.getString("organization_id") + "\">"
								+ rs.getString("orgname") + "</option>";
					} else {
						city += "<option value=\""
								+ rs.getString("organization_id") + "\">"
								+ rs.getString("orgname") + "</option>";
					}
				}

				sql = "select * from sys_t_organization org where org.parentorgid = substr('"
						+ oldOrgId
						+ "', 1, 4) and org. organization_id <> substr('"
						+ oldOrgId + "', 1, 6) order by org.organization_id";
				ps = con.prepareStatement(sql);
				rs = ps.executeQuery();
				html += "<tr valign=\"middle\"><td width=\"80\" height=\"25\">选择所迁往</td><td valign=\"middle\">市：<select id =\"city\" onchange=\"getNextorg(this.options[this.selectedIndex].value,"+oldOrgId+")\">"
						+ city
						+ "</select>  县（市、区）&nbsp;&nbsp;<span id =\"ll\"> <select id=\"county\" name=\"county\"><option value=\"\">未选择...</option>";
				while (rs.next()) {
					html += "<option value=\""
							+ rs.getString("organization_id") + "\">"
							+ rs.getString("orgname") + "</option>";
				}
				html += "</select></span></td></tr></table>";
				request.setAttribute("html", html);
			}
			tx.commit();
		} catch (SQLException e) {
			tx.rollback();
			e.printStackTrace();
		} finally {
			try {
				if (rs != null) {
					rs.close();
				}
				if (ps != null) {
					ps.close();
				}
				if (con != null) {
					con.close();
				}
				session.close();
			} catch (SQLException e) {
			}
		}

		return mapping.findForward("moveexternalout");
	}
}