/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system.menu;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.log4j.Log4jApp;
import com.mingda.dao.SysTPrivilegeDAO;
import com.mingda.entity.SysTPrivilege;

/**
 * MyEclipse Struts Creation date: 09-16-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="menuedit" path="/page/system/menu/menuedit.jsp"
 */
public class MenusaveAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String privilegeId = request.getParameter("privilegeId");
		String parentprivilegeid = request.getParameter("parentprivilegeid");
		String displayname = request.getParameter("displayname");
		String url = request.getParameter("url");
		String target = request.getParameter("target");
		String detail = request.getParameter("detail");
		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		SysTPrivilege privilege = new SysTPrivilege();
		SysTPrivilege pprivilege = null;
		try {
			SysTPrivilegeDAO pdao = new SysTPrivilegeDAO();
			pprivilege = pdao.findById(new Long(parentprivilegeid));
			if (null == pprivilege) {
				pprivilege = new SysTPrivilege();
				pprivilege.setDepth(new Long(0));
				pprivilege.setDisplayname("");
				pprivilege.setSequence(".");
				pprivilege.setNav("");
			}
			String temp = "";
			if (!"".equals(pprivilege.getNav())) {
				temp = pprivilege.getNav() + ">>";
			}
			Log4jApp.logger("导航::" + temp);
			if (null == privilegeId || "".equals(privilegeId)) {
				List sons = pdao.findByParentprivilegeid(new Long(
						parentprivilegeid));
				privilege.setParentprivilegeid(new Long(parentprivilegeid));
				privilege.setDisplayname(displayname);
				privilege.setTarget(target);
				privilege.setDepth(new Long(
						pprivilege.getDepth().longValue() + 1));
				Log4jApp.logger("导航::" + temp + privilege.getDisplayname());
				privilege.setNav(temp + privilege.getDisplayname());
				privilege.setStatus("1");
				Log4jApp.logger("序列::" + pprivilege.getSequence() + sons.size()
						+ ".");
				privilege.setSequence(pprivilege.getSequence() + sons.size()
						+ ".");
				privilege.setDetail(detail);
				privilege.setUrl(url);
			} else {
				privilege = pdao.findById(new Long(privilegeId));
				privilege.setParentprivilegeid(new Long(parentprivilegeid));
				privilege.setDisplayname(displayname);
				privilege.setTarget(target);
				Log4jApp.logger("导航::" + temp + privilege.getDisplayname());
				privilege.setNav(temp + privilege.getDisplayname());
				privilege.setDetail(detail);
				privilege.setUrl(url);

			}
			privilege = pdao.save(privilege);
			tx.commit();
		} catch (Exception ex) {
			tx.rollback();
			ex.printStackTrace();
		} finally {
			SessionFactory.closeSession();
		}
		try {
			PrintWriter out = response.getWriter();
			out
					.println("<script>parent.parent.frames['leftFrame'].location.reload('menutree.do?menuid="
							+ privilege.getPrivilegeId() + "');parent.parent.frames['mainFrame'].location.reload('menudetail.jsp');</script>");
			out.flush();
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
		// return mapping.findForward("menuedit");
	}
}