/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.undo;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;

/**
 * MyEclipse Struts Creation date: 12-06-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="moveoutundo"
 *                        path="/page/info/undo/moveoutundo.jsp"
 */
public class MoveoutundoAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String familyid = request.getParameter("familyid");
		String familymoveid = request.getParameter("familymoveid");

		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		// Connection con = null;
		// PreparedStatement ps = null;
		// ResultSet rs = null;
		try {
			if (null == familyid || null == familymoveid) {
			} else {
				String sql = "select mo.nfamilyno  , fam.mastername ,mo.isover , mo.ofamilyno from biz_t_familymove mo ,info_t_family fam where  mo.familymove_id='"
						+ familymoveid + "' and fam.family_id =mo.family_id ";
				List rs = session.createSQLQuery(sql).list();
				boolean flag = false;
				if (null != rs && rs.size() == 1) {
					Object[] o = (Object[]) rs.get(0);
					String[] s = new String[o.length];

					for (int i = 0; i < o.length; i++) {
						if (null != o[i]) {
							s[i] = o[i].toString();
						} else {
							s[i] = "";
						}
					}

					if ("0".equals(s[2])) {
						flag = true;
					} else {
						flag = false;
						if (null == s[0]
								|| "".equals(s[0])
								|| "null".equals(s[0])) {
							request.setAttribute("resultstr", "此户已经被撤销，户主姓名："
									+ s[1] + " 家庭编号："
									+ s[3]);

						} else {
							request.setAttribute("resultstr", "此户已经被迁入 ，户主姓名："
									+ s[1] + "  新家庭编号："
									+ s[0]);
						}
					}
				}
				if (flag) {
					// 是否需要处理 业务 实施发放 ？？？？
					sql = "update  biz_t_familymove mo set mo.isover ='1' where mo.familymove_id ='"
							+ familymoveid + "'";
					//log.debug(sql);
					session.createSQLQuery(sql).executeUpdate();
					sql = "update info_t_family fam set fam.status ='1' , fam.tohtml='1' where fam.family_id='"
							+ familyid + "'";
					//log.debug(sql);
					session.createSQLQuery(sql).executeUpdate();
					request.setAttribute("resultstr", "恢复成功，可以重新迁移");
				}
			}
			tx.commit();
		} catch (Exception ex) {
			tx.rollback();
			ex.printStackTrace();
		} finally {
			session.close();
		}
		return mapping.findForward("moveoutundo");
	}
}