/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.report;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.action.querymanage.QueryManagePolicy;
import com.mingda.common.SessionFactory;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 03-04-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="reportnational"
 *                        path="/page/report/report_national.jsp"
 */
public class ReportAction extends Action {
	static Logger log = Logger.getLogger(ReportAction.class);

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("deprecation")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ArrayList list = new ArrayList();
		String reportname = request.getParameter("reportname");
		String month = request.getParameter("month");
		String y = "";
		String m = "";
		if (month.length() >=4) {
			log.debug(month.substring(0, 4));
			log.debug(month.substring(4, 5));
			y = month.substring(0, 4);
			m = month.substring(4, month.length());
		}
		HttpSession session = request.getSession();
		SysTEmployee employee = (SysTEmployee) session.getAttribute("employee");

		// log.debug(employee.getSysTOrganization().getOrganizationId());

		/*
		 * ActionForward forward = new ActionForward(
		 * "/page/sysreport/ReportEngineView.jsp?Sys_ReportName=" + reportname +
		 * "&Sys_mon=" + month + "&Sys_orgno=" +
		 * employee.getSysTOrganization().getOrganizationId());
		 * forward.setRedirect(true);
		 */
		Session hsession = SessionFactory.getSession();
		Connection conn = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		String sql = "";
		try {
			if (employee.getSysTOrganization().getOrganizationId().length() == 2) {
				/*
				 * sql = "select os.renkou, " + " hs, " + " ss, " +
				 * " round((ss / os.renkou) * 10000) / 100 || '%' as bl1, " +
				 * " zm, " + " round((zm / ss) * 100) / 100 as bl2, " +
				 * " os.biaozhun, " + " zdhs, " + " zdss, " +
				 * " round((zdhs / hs) * 10000) / 100 || '%' as zdbl1, " +
				 * " zdzm, " + " round((zdzm / zdss) * 100) / 100 as zdbl2, " +
				 * " ybhs, " + " ybss, " +
				 * " round((ybhs / hs) * 10000) / 100 || '%' as ybbl1, " +
				 * " ybzm, " + " round((ybzm / ybss) * 100) / 100 as ybbl2, " +
				 * " decode(temp, 0, os.oname,  " + " (select oo.orgname  " +
				 * " from sys_t_organization oo  " +
				 * " where oo.organization_id = a.oid)) as oname  " + " from ("
				 * + "select count(*) as hs, "+ " sum(ck.checkmoney) as zm, "+
				 * " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as rs, "
				 * +
				 * " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as ss, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, 1, 877, 1, 878, 1, 0)) as zdhs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype),  876, ck.checkmoney, 877, ck.checkmoney, 878, ck.checkmoney, 0)) as zdzm, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), "
				 * +
				 * " 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as zdrs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  0)) as zdss, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, 1, 874, 1, 875, 1, 0)) as ybhs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, ck.checkmoney, "
				 * + " 874,  ck.checkmoney,  875, ck.checkmoney, 0)) as ybzm, "+
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 875, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybrs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  875, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybss, "
				 * + " org.organization_id as oid, 0 as temp " +
				 * " from biz_t_optacc       m, " + " impl_t_accoptcheck ck, " +
				 * " info_t_family      fam, " + " sys_t_organization org " +
				 * " where m.accyear = '" + y + "' " + " and m.accmonth = '" + m
				 * + "' " + " and m.accflag = '2' " +
				 * " and m.optacc_id = ck.optacc_id " +
				 * " and ck.policy_id = '21' " +
				 * " and fam.family_id = ck.family_id " +
				 * " and fam.organization_id like org.organization_id || '%' " +
				 * " and (org.depth = 1 or org.depth = 2) " +
				 * " group by org.organization_id " + " union "+
				 * "select count(*) as hs, "+ " sum(ck.checkmoney) as zm, "+
				 * " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as rs, "
				 * +
				 * " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as ss, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, 1, 877, 1, 878, 1, 0)) as zdhs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype),  876, ck.checkmoney, 877, ck.checkmoney, 878, ck.checkmoney, 0)) as zdzm, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), "
				 * +
				 * " 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as zdrs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  0)) as zdss, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, 1, 874, 1, 875, 1, 0)) as ybhs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, ck.checkmoney, "
				 * + " 874,  ck.checkmoney,  875, ck.checkmoney, 0)) as ybzm, "+
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 875, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybrs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  875, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybss, "
				 * + "   substr(org.organization_id, 1, 4) as oid , 1 as temp "
				 * + " from biz_t_optacc       m, " + " impl_t_accoptcheck ck, "
				 * + " info_t_family      fam, " + " sys_t_organization org " +
				 * " where m.accyear = '" + y + "' " + " and m.accmonth = '" + m
				 * + "' " + " and m.accflag = '2' " +
				 * " and m.optacc_id = ck.optacc_id " +
				 * " and ck.policy_id = '21' " +
				 * " and fam.family_id = ck.family_id " +
				 * " and fam.organization_id like org.organization_id || '%' " +
				 * " and (org.depth = 3 and org.zone = 1) " +
				 * " group by substr(org.organization_id, 1, 4) " + " union "+
				 * "select count(*) as hs, "+ " sum(ck.checkmoney) as zm, "+
				 * " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as rs, "
				 * +
				 * " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as ss, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, 1, 877, 1, 878, 1, 0)) as zdhs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype),  876, ck.checkmoney, 877, ck.checkmoney, 878, ck.checkmoney, 0)) as zdzm, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), "
				 * +
				 * " 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as zdrs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
				 * +
				 * " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  0)) as zdss, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, 1, 874, 1, 875, 1, 0)) as ybhs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, ck.checkmoney, "
				 * + " 874,  ck.checkmoney,  875, ck.checkmoney, 0)) as ybzm, "+
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 875, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybrs, "
				 * +
				 * " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  875, "
				 * +
				 * " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybss, "
				 * + " org.organization_id as oid, 0 as temp " +
				 * " from biz_t_optacc       m, " + " impl_t_accoptcheck ck, " +
				 * " info_t_family      fam, " + " sys_t_organization org " +
				 * " where m.accyear = '" + y + "' " + " and m.accmonth = '" + m
				 * + "' " + " and m.accflag = '2' " +
				 * " and m.optacc_id = ck.optacc_id " +
				 * " and ck.policy_id = '21' " +
				 * " and fam.family_id = ck.family_id " +
				 * " and fam.organization_id like org.organization_id || '%' " +
				 * " and (org.depth = 3 and org.zone is null) " +
				 * " group by org.organization_id) a, " + " orgstat os " +
				 * " where a.oid = os.oid " + " order by os.oid";
				 */
				sql = "select   HS,  SS,  ZM  ,YBHS , YBSS , YBZM , ZDHS , ZDSS , ZDZM,"
						+ " decode (os.renkou,null,0,0, 0, round( ( SS/os.renkou)*10000)/100) bl1 , "
						+ " decode (SS,0, 0,  (round  (ZM/SS)*100)/100 ) as bl2, "
						+ " decode (HS,0, 0, round( ( YBHS/HS)*10000)/100)       as ybbl1, "
						+ " decode (YBSS,0, 0,  (round  (YBZM/YBSS)*100)/100 )      as ybbl2 , "
						+ " decode (HS,0, 0, round( ( ZDHS/HS)*10000)/100)       as zdbl1, "
						+ " decode (ZDSS,0, 0,  (round  (ZDZM/ZDSS)*100)/100 )      as zdbl2 , "
						+ " os.renkou,os.biaozhun ,  decode(TEMP,1,(select p.orgname from sys_t_organization p where p.organization_id=a.ORGANIZATION_ID), os.oname ) as oname from orgstat os ,( "
						+ " select '0' as temp , sum(HS) as hs,  sum(SS) as ss,  sum(ZM) as zm , sum(YBHS) as ybhs , sum(YBSS) as ybss , sum(YBZM) as ybzm , sum(ZDHS) as zdhs , sum(ZDSS) as ZDSS , sum(ZDZM) as zdzm, oo.organization_id as organization_id   from sys_t_organization oo , ( "
						+ " select nvl(HS,0) as hs , nvl( SS,0) as ss , nvl(ZM,0) as zm, nvl( YBHS,0) as ybhs , "
						+ " nvl( YBSS,0) as ybss, nvl( YBZM ,0) as ybzm, nvl( ZDHS ,0) as zdhs, nvl(ZDSS ,0) as zdss , "
						+ " nvl(ZDZM,0) as zdzm ,t. ORGANIZATION_ID  "
						+ " from sys_t_organization t left join  (select sum(decode(ck.saltype,873,1,874,1,875,1,876,1,877,1,878,1,0)) as hs,  sum(ck.populaiton) as ss , sum(ck.countmoney) as zm ,  "
						+ " sum(decode(ck.saltype,873,1,874,1,875,1,0)) as ybhs,  "
						+ " sum(decode(ck.saltype,873,ck.populaiton,874,ck.populaiton,875,ck.populaiton,0)) as ybss,  "
						+ " sum(decode(ck.saltype,873,ck.countmoney,874,ck.countmoney,875,ck.countmoney,0)) as ybzm,  "
						+ " sum(decode(ck.saltype,876,1,877,1,878,1,0)) as zdhs,  "
						+ " sum(decode(ck.saltype,876,ck.populaiton,877,ck.populaiton,878,ck.populaiton,0)) as zdss,  "
						+ " sum(decode(ck.saltype,876,ck.countmoney,877,ck.countmoney,878,ck.countmoney,0)) as zdzm "
						+ " , org.organization_id "
						+ " from biz_t_optacc       m, "
						+ " impl_t_accoptcheck ck, "
						+ " info_t_family      fam, "
						+ " sys_t_organization org " + " where m.accyear = '"
						+ y
						+ "' "
						+ " and m.accmonth = '"
						+ m
						+ "' "
						+ " and m.accflag = '2' "
						+ " and m.optacc_id = ck.optacc_id "
						+ " and ck.policy_id = '21' "
						+ " and fam.family_id = ck.family_id "
						+ " and fam.familyno like org.organization_id || '%' "
						+ " and org.depth = 3 "
						+ " and org.status = 1 "
						+ " group by org.organization_id ) mv on  mv.ORGANIZATION_ID =t.organization_id where t.depth=3 and t.status=1 ) tt where tt.organization_id like  oo.organization_id||'%' and  "
						+ " (oo.depth=1 or oo.depth=2) group by oo.organization_id "
						+ " union  "
						+ " select  '1' as temp ,sum(HS) as hs,  sum(SS) as ss,  sum(ZM) as zm , sum(YBHS) as ybhs , sum(YBSS) as ybss , sum(YBZM) as ybzm , sum(ZDHS) as zdhs , sum(ZDSS) as ZDSS , sum(ZDZM) as zdzm, substr(oo.organization_id,1,4)  as organization_id  from sys_t_organization oo , ( "
						+ " select nvl(HS,0) as hs , nvl( SS,0) as ss , nvl(ZM,0) as zm, nvl( YBHS,0) as ybhs , "
						+ " nvl( YBSS,0) as ybss, nvl( YBZM ,0) as ybzm, nvl( ZDHS ,0) as zdhs, nvl(ZDSS ,0) as zdss , "
						+ " nvl(ZDZM,0) as zdzm ,t. ORGANIZATION_ID  "
						+ " from sys_t_organization t left join  (select sum(decode(ck.saltype,873,1,874,1,875,1,876,1,877,1,878,1,0)) as hs,  sum(ck.populaiton) as ss , sum(ck.countmoney) as zm ,  "
						+ " sum(decode(ck.saltype,873,1,874,1,875,1,0)) as ybhs,  "
						+ " sum(decode(ck.saltype,873,ck.populaiton,874,ck.populaiton,875,ck.populaiton,0)) as ybss,  "
						+ " sum(decode(ck.saltype,873,ck.countmoney,874,ck.countmoney,875,ck.countmoney,0)) as ybzm,  "
						+ " sum(decode(ck.saltype,876,1,877,1,878,1,0)) as zdhs,  "
						+ " sum(decode(ck.saltype,876,ck.populaiton,877,ck.populaiton,878,ck.populaiton,0)) as zdss,  "
						+ " sum(decode(ck.saltype,876,ck.countmoney,877,ck.countmoney,878,ck.countmoney,0)) as zdzm "
						+ " , org.organization_id "
						+ " from biz_t_optacc       m, "
						+ "      impl_t_accoptcheck ck, "
						+ " info_t_family      fam, "
						+ "  sys_t_organization org "
						+ " where m.accyear = '"
						+ y
						+ "' "
						+ " and m.accmonth = '"
						+ m
						+ "' "
						+ " and m.accflag = '2' "
						+ " and m.optacc_id = ck.optacc_id "
						+ " and ck.policy_id = '21' "
						+ " and fam.family_id = ck.family_id "
						+ " and fam.familyno like org.organization_id || '%' "
						+ " and org.depth = 3 "
						+ "  and org.status = 1 "
						+ " group by org.organization_id ) mv on  mv.ORGANIZATION_ID =t.organization_id where t.depth=3 and t.status=1 ) tt where tt.organization_id like  oo.organization_id||'%' and  "
						+ " (oo.depth=3 and oo.zone=1) group by  substr(oo.organization_id,1,4) "
						+ " union  "
						+ " select '0' as temp ,sum(HS) as hs,  sum(SS) as ss,  sum(ZM) as zm , sum(YBHS) as ybhs , sum(YBSS) as ybss , sum(YBZM) as ybzm , sum(ZDHS) as zdhs , sum(ZDSS) as ZDSS , sum(ZDZM) as zdzm, oo.organization_id  as organization_id  from sys_t_organization oo , ( "
						+ " select nvl(HS,0) as hs , nvl( SS,0) as ss , nvl(ZM,0) as zm, nvl( YBHS,0) as ybhs , "
						+ " nvl( YBSS,0) as ybss, nvl( YBZM ,0) as ybzm, nvl( ZDHS ,0) as zdhs, nvl(ZDSS ,0) as zdss , "
						+ " nvl(ZDZM,0) as zdzm ,t. ORGANIZATION_ID  "
						+ " from sys_t_organization t left join  (select sum(decode(ck.saltype,873,1,874,1,875,1,876,1,877,1,878,1,0)) as hs,  sum(ck.populaiton) as ss , sum(ck.countmoney) as zm ,  "
						+ " sum(decode(ck.saltype,873,1,874,1,875,1,0)) as ybhs,  "
						+ " sum(decode(ck.saltype,873,ck.populaiton,874,ck.populaiton,875,ck.populaiton,0)) as ybss,  "
						+ " sum(decode(ck.saltype,873,ck.countmoney,874,ck.countmoney,875,ck.countmoney,0)) as ybzm,  "
						+ " sum(decode(ck.saltype,876,1,877,1,878,1,0)) as zdhs,  "
						+ " sum(decode(ck.saltype,876,ck.populaiton,877,ck.populaiton,878,ck.populaiton,0)) as zdss,  "
						+ " sum(decode(ck.saltype,876,ck.countmoney,877,ck.countmoney,878,ck.countmoney,0)) as zdzm "
						+ " , org.organization_id "
						+ " from biz_t_optacc       m, "
						+ " impl_t_accoptcheck ck, "
						+ " info_t_family      fam, "
						+ " sys_t_organization org "
						+ " where m.accyear = '"
						+ y
						+ "' "
						+ " and m.accmonth = '"
						+ m
						+ "' "
						+ " and m.accflag = '2' "
						+ " and m.optacc_id = ck.optacc_id "
						+ " and ck.policy_id = '21' "
						+ " and fam.family_id = ck.family_id "
						+ " and fam.familyno like org.organization_id || '%' "
						+ " and org.depth = 3 "
						+ " and org.status = 1 "
						+ " group by org.organization_id ) mv on  mv.ORGANIZATION_ID =t.organization_id where t.depth=3 and t.status=1 ) tt where tt.organization_id like  oo.organization_id||'%' and  "
						+ " (oo.depth=3 and oo.zone is null) group by   oo.organization_id ) a where a.ORGANIZATION_ID =os.oid order by a.ORGANIZATION_ID";

			} else {
				sql = "select null as renkou, hs, ss, null as bl1, "
						+ " zm, round((zm / ss) * 100) / 100 as bl2, null as BIAOZHUN, "
						+ " zdhs,  zdss, "
						+ " decode(hs,0,0 , round((zdhs / hs) * 10000) / 100 )|| '%' as zdbl1, zdzm, "
						+ " decode(zdss,0,0,round((zdzm / zdss) * 100) / 100 )  as zdbl2, "
						+ " ybhs,  ybss, decode(hs,0,0, round((ybhs / hs) * 10000) / 100 )|| '%' as ybbl1, "
						+ " ybzm,  decode(ybss,0,0,  round((ybzm / ybss) * 100) / 100 ) as ybbl2, os.orgname as oname "
						+ "  from ("
						+ "select count(*) as hs, "
						+ " sum(ck.checkmoney) as zm, "
						+ " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as rs, "
						+ " sum(decode(ck.populaiton,null,fam.ensurecount , ck.populaiton)) as ss, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, 1, 877, 1, 878, 1, 0)) as zdhs, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype),  876, ck.checkmoney, 877, ck.checkmoney, 878, ck.checkmoney, 0)) as zdzm, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), "
						+ " 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
						+ " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
						+ " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as zdrs, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 876, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
						+ " 877, decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), "
						+ " 878,  decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  0)) as zdss, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, 1, 874, 1, 875, 1, 0)) as ybhs, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, ck.checkmoney, "
						+ " 874,  ck.checkmoney,  875, ck.checkmoney, 0)) as ybzm, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
						+ " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
						+ " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 875, "
						+ " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybrs, "
						+ " sum(decode(decode(ck.saltype,null,fam.saltype,ck.saltype), 873, "
						+ " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 874, "
						+ " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton),  875, "
						+ " decode(ck.populaiton,null,fam.ensurecount , ck.populaiton), 0)) as ybss, "
						+ " org.organization_id as oid, 0 as temp "
						+ " from biz_t_optacc       m, "
						+ " impl_t_accoptcheck ck, "
						+ " info_t_family      fam, "
						+ " sys_t_organization org "
						+ " where m.accyear = '"
						+ y
						+ "' "
						+ " and m.accmonth = '"
						+ m
						+ "' "
						+ " and m.accflag = '2' "
						+ " and m.optacc_id = ck.optacc_id "
						+ " and ck.policy_id = '21' "
						+ " and fam.family_id = ck.family_id "
						+ " and fam.organization_id like org.organization_id || '%' "
						+ " and (org.organization_id ='"
						+ employee.getSysTOrganization().getOrganizationId()
						+ "' or org.parentorgid='"
						+ employee.getSysTOrganization().getOrganizationId()
						+ "') " + " group by org.organization_id) a, "
						+ " sys_t_organization os "
						+ " where a.oid = os.organization_id "
						+ " order by os.organization_id";
			}
			log.debug("aa>>>" + sql);
			conn = hsession.connection();
			pstmt = conn.prepareStatement(sql);
			rs = pstmt.executeQuery();
			while (rs.next()) {
				StatDTO e = new StatDTO();
				e.setRenkou(rs.getString("RENKOU"));
				e.setHs(rs.getString("HS"));
				e.setSs(rs.getString("SS"));
				e.setBl1(rs.getString("BL1"));
				e.setZm(rs.getString("ZM"));
				e.setBl2(rs.getString("BL2"));
				e.setBiaozhun(rs.getString("BIAOZHUN"));
				e.setZdhs(rs.getString("ZDHS"));
				e.setZdss(rs.getString("ZDSS"));
				e.setZdbl1(rs.getString("ZDBL1"));
				e.setZdzm(rs.getString("ZDZM"));
				e.setZdbl2(rs.getString("ZDBL2"));
				e.setYbhs(rs.getString("YBHS"));
				e.setYbss(rs.getString("YBSS"));
				e.setYbbl1(rs.getString("YBBL1"));
				e.setYbzm(rs.getString("YBZM"));
				e.setYbbl2(rs.getString("YBBL2"));
				e.setOname(rs.getString("ONAME"));
				list.add(e);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			try {
				if (rs != null) {
					rs.close();
				}
				if (pstmt != null) {
					pstmt.close();
				}
				if (conn != null) {
					conn.close();
				}
				SessionFactory.closeSession();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		request.setAttribute("statlist", list);
		return mapping.findForward("reportnational1");
	}
}