package com.mingda.common.ibatis.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

import com.mingda.common.ibatis.data.SysTInfolog;
import com.mingda.common.ibatis.data.SysTInfologExample;

public interface SysTInfologDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int countByExample(SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int deleteByExample(SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int deleteByPrimaryKey(BigDecimal infologId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    void insert(SysTInfolog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    void insertSelective(SysTInfolog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    List selectByExampleWithBLOBs(SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    List selectByExampleWithoutBLOBs(SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    SysTInfolog selectByPrimaryKey(BigDecimal infologId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int updateByExampleSelective(SysTInfolog record, SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int updateByExampleWithBLOBs(SysTInfolog record, SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int updateByExampleWithoutBLOBs(SysTInfolog record, SysTInfologExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int updateByPrimaryKeySelective(SysTInfolog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int updateByPrimaryKeyWithBLOBs(SysTInfolog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SUMMER.SYS_T_INFOLOG
     *
     * @ibatorgenerated Fri Jul 24 14:47:41 CST 2009
     */
    int updateByPrimaryKeyWithoutBLOBs(SysTInfolog record) throws SQLException;
}