/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.form.info.search;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="familyQueryForm"
 */
public class FamilyQueryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** value property */
	private String value;

	/** term property */
	private String term;

	/** organizationId property */
	private String organizationId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	/** 
	 * Returns the value.
	 * @return String
	 */
	public String getValue() {
		return value;
	}

	/** 
	 * Set the value.
	 * @param value The value to set
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/** 
	 * Returns the term.
	 * @return String
	 */
	public String getTerm() {
		return term;
	}

	/** 
	 * Set the term.
	 * @param term The term to set
	 */
	public void setTerm(String term) {
		this.term = term;
	}

	/** 
	 * Returns the organizationId.
	 * @return String
	 */
	public String getOrganizationId() {
		return organizationId;
	}

	/** 
	 * Set the organizationId.
	 * @param organizationId The organizationId to set
	 */
	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}
}