/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.policy.account;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.action.policy.comm.PublicComm;
import com.mingda.common.myjdbc.ConnectionManager;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AccountpageAction extends Action {
	static Logger log = Logger.getLogger(AccountpageAction.class);
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 获取action
		String action = request.getParameter("action");		
		//log.debug(action);		
		//
		response.setContentType("text/html; charset=UTF-8");
		
		try {
			request.setCharacterEncoding("UTF-8");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		
		//
		try {
			PrintWriter out = response.getWriter();
			//
			if("getPolicySelect".equals(action)){
				//
				String sname = request.getParameter("sname");
				String mode = request.getParameter("mode");
				log.debug("sname"+sname+">>>mode="+mode);
				PublicComm pubilccomm = new PublicComm();
				out.print(pubilccomm.getPolicySelect(sname, mode));
			}else if("getSysTimeFormatDate".equals(action)){
				PublicComm pubilccomm = new PublicComm();
				out.print(pubilccomm.getSysTimeFormatDate());
			}else if("getPolicyAccTable".equals(action)){
				//
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				String jpid = request.getParameter("jpid");
				String jacc = request.getParameter("jacc");
				//
				String jyear = request.getParameter("jyear");
				String jmonth = request.getParameter("jmonth");
				String jdesc = request.getParameter("jdesc");
				String jbegdt = request.getParameter("jbegdt");
				String jenddt = request.getParameter("jenddt");
				//
				String jbegpage = request.getParameter("jbegpage");
				String jendpage = request.getParameter("jendpage");
				//
				String jqdeptid = request.getParameter("jqdeptid");
				//
				jdesc = URLDecoder.decode(jdesc, "UTF-8");
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	hashmap.put("jpid", jpid);
            	//
            	hashmap.put("jacc", jacc);
            	//
            	hashmap.put("jyear", jyear);
            	hashmap.put("jmonth", jmonth);
            	hashmap.put("jdesc", jdesc);
            	hashmap.put("jbegdt", jbegdt);
            	hashmap.put("jenddt", jenddt);
            	//
            	hashmap.put("jbegpage", jbegpage);
            	hashmap.put("jendpage", jendpage);
            	//
            	hashmap.put("jqdeptid", jqdeptid);
            	
				Accountpage accountpage = new Accountpage();
				out.print(accountpage.getPolicyAccTable(hashmap));
			}else if(action.equals("addPolicyNowAcc")){
				//
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				String jpid = request.getParameter("jpid");
				//
				String jyear = request.getParameter("jyear");
				String jmonth = request.getParameter("jmonth");
				String jdesc = request.getParameter("jdesc");
				String jbegdt = request.getParameter("jbegdt");
				String jenddt = request.getParameter("jenddt");
				String jmoneyflag = request.getParameter("jmoneyflag");
				String jmoney = request.getParameter("jmoney");
				//
				jdesc = URLDecoder.decode(jdesc, "UTF-8");
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	hashmap.put("jpid", jpid);
            	//
            	hashmap.put("jyear", jyear);
            	hashmap.put("jmonth", jmonth);
            	hashmap.put("jdesc", jdesc);
            	hashmap.put("jbegdt", jbegdt);
            	hashmap.put("jenddt", jenddt);
            	hashmap.put("jmoneyflag", jmoneyflag);
            	hashmap.put("jmoney", jmoney);
            	//
				Accountpage accountpage = new Accountpage();
				out.print(accountpage.addPolicyNowAcc(hashmap));
			}else if("delPolicyNowAcc".equals(action)){
				//
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				String jpid = request.getParameter("jpid");
				//
				String jaccid = request.getParameter("jaccid");
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	hashmap.put("jpid", jpid);
            	//
            	hashmap.put("jaccid", jaccid);
            	//
				Accountpage accountpage = new Accountpage();
				out.print(accountpage.delPolicyNowAcc(hashmap));
			}else if("accPolicyNowAcc".equals(action)){
				//
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				String jpid = request.getParameter("jpid");
				//
				String jaccid = request.getParameter("jaccid");
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	hashmap.put("jpid", jpid);
            	//
            	hashmap.put("jaccid", jaccid);
            	//
				Accountpage accountpage = new Accountpage();
				out.print(accountpage.accPolicyNowAcc(hashmap));
			}
		} catch (IOException e) {
			e.printStackTrace();
		}finally{
			log.debug("关闭开始------------");
			ConnectionManager.closeQuietly();
			log.debug("关闭结束------------");
		}
		return null;
	}
}