/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.info.search;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Transaction;

import com.mingda.common.Pager;
import com.mingda.common.SessionFactory;
import com.mingda.entity.SysTEmployee;
import com.mingda.form.info.search.FamilyQueryForm;

/**
 * MyEclipse Struts Creation date: 04-24-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/info/search/familyQuery" name="familyQueryForm"
 *                input="/form/familyQuery.jsp" scope="request" validate="true"
 * @struts.action-forward name="familyquery"
 *                        path="/page/info/search/familyquery.jsp"
 */
public class FamilyQueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FamilyQueryForm familyQueryForm = (FamilyQueryForm) form;
		String cur_page = request.getParameter("cur_page");// 取得当前页面
		String organizationId = request.getParameter("organizationId");
		HttpSession httpsession = request.getSession();
		if (organizationId == null || organizationId.equals("")
				|| organizationId.equals("null")) {
			SysTEmployee sysTEmployee = (SysTEmployee) httpsession
					.getAttribute("employee");
			organizationId = sysTEmployee.getSysTOrganization()
					.getOrganizationId();
		}
		Transaction tx = SessionFactory.getSession().beginTransaction();
		String sql = "";
		Pager pager = null;
		try {

			if (cur_page == null) {
				if (familyQueryForm.getTerm().equals("all")) {
					sql = "";
				} else if (familyQueryForm.getTerm().equals("mastername")) {
					sql = " and exists (select 1 from f.infoTMembers fms where fms.membername like '"
							+ familyQueryForm.getValue() + "%') ";
				} else {
					sql = " and f." + familyQueryForm.getTerm() + " = "
							+ familyQueryForm.getValue();
				}
				sql = "select f from InfoTFamily f where f.status=1 " + sql
						+ "and f.sysTOrganization like '" + organizationId
						+ "%' order by f.familyno";
				pager = new Pager(0,0,"");
				httpsession.setAttribute("pager", pager);
			} else {
				pager = (Pager) httpsession.getAttribute("pager");
				Integer i = new Integer(cur_page);
				pager.setPage(i.intValue());
			}
			pager.setUrl("familyQuery.do?organizationId=" + organizationId);
			List list =null;
			if (list != null && list.size() > 0) {
				request.setAttribute("list", list);
				request.setAttribute("toolsmenu", pager.getToolsMenu());
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		} finally {
			SessionFactory.closeSession();
		}
		return mapping.findForward("familyquery");
	}
}