/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system.dictionary;

import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;

/**
 * MyEclipse Struts Creation date: 08-07-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="dictsort"
 *                        path="/page/system/dictionary/dictsort.jsp"
 */
public class DictsortinitAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	static Logger log =Logger.getLogger(DictsortinitAction.class);
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Document dict = (Document) this.servlet.getServletContext()
				.getAttribute("dictionary");
		log.debug(dict.asXML());
		Document doc = DocumentHelper.createDocument();
		doc.setXMLEncoding("GB18030");
		// border="0" cellspacing="0" cellpadding="0"
		Element table = doc.addElement("table").addAttribute("class", "table1")
				.addAttribute("width", "100%").addAttribute("border", "0")
				.addAttribute("cellspacing", "0").addAttribute("cellpadding",
						"0");
		Element tr = table.addElement("tr");
		tr.addElement("th").setText("字典类别");
		tr.addElement("th").setText("操作");
		tr.addElement("th").setText("状态");
		List list = dict.selectNodes("//DICTSORT");
		Iterator it = list.iterator();
		while (it.hasNext()) {
			Element element = (Element) it.next();
			if ("0".equals(element.attributeValue("isread"))) {
				tr = table.addElement("tr");
				tr.addElement("td").addElement("a").addAttribute("href",
						"dictvalueinit.do?id=" + element.attributeValue("id"))
						.addAttribute("target", "mainFrame").setText(
								element.attributeValue("title"));
				tr.addElement("td").addElement("span").addAttribute("onclick", "viewdict("+element.attributeValue("id")+")").setText("修改");
				String status = "在用";
				if ("0".equals(element.attributeValue("status"))) {
					status = "停用";
				}
				tr.addElement("td").setText(status);
			}
		}
		log.debug(dict.asXML());
		request.setAttribute("table", table.asXML());
		return mapping.findForward("dictsort");
	}
}