/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system.dictionary;
import java.util.Iterator;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
/**
 * MyEclipse Struts Creation date: 08-07-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="dictvalue"
 *                        path="/page/system/dictionary/dictvalue.jsp"
 */
public class DictvalueinitAction extends Action {
	/*
	 * Generated Methods
	 */
	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String dsid = request.getParameter("id");
		Document dict = (Document) this.servlet.getServletContext()
				.getAttribute("dictionary");
		Document doc = DocumentHelper.createDocument();
		doc.setXMLEncoding("GB18030");
		// border="0" cellspacing="0" cellpadding="0"
		Element table = doc.addElement("table").addAttribute("class", "table1")
				.addAttribute("id", "main").addAttribute("width", "100%")
				.addAttribute("border", "0").addAttribute("cellspacing", "0")
				.addAttribute("cellpadding", "0");
		Element tr = table.addElement("tr");
		tr.addElement("th").setText("ÐòºÅ");
		tr.addElement("th").setText("×ÖµäÖµ");
		tr.addElement("th").setText("×´Ì¬");
		Element ds = (Element) dict.selectSingleNode("//DICTSORT[@id='" + dsid
				+ "']");
		Iterator it = ds.elementIterator();
		while (it.hasNext()) {
			Element element = (Element) it.next();
			String dvid = element.attributeValue("id");
			tr = table.addElement("tr");
			tr.addElement("td").setText(element.attributeValue("sequence"));
			Element td = tr.addElement("td").addAttribute("width", "180px");
			td.addElement("span").addAttribute("class", "cursor:hand").addAttribute("width", "100%").addAttribute(
					"id", "dv" + dvid).addAttribute("ondblclick",
					"changeText(" + dvid + "," + dsid + ",this)").setText(
					element.getText());
			td.addElement("span").addAttribute("class", "cursor:hand").addAttribute("style", "display:none")
					.addAttribute("id", "ev" + dvid).addElement("input")
					.addAttribute("name", "dvtext").addAttribute("style",
							"width:100%").addAttribute("value",
							element.getText()).addAttribute("onchange",
							"onsave(" + dvid + "," + dsid + ",this)");
			String status = "ÔÚÓÃ";
			if (element.attributeValue("status").equals("0")) {
				status = "Í£ÓÃ";
			}
			tr.addElement("td").addElement("span").addAttribute("class", "cursor:hand").addAttribute("id",
					"s" + element.attributeValue("id")).addAttribute(
					"onclick",
					"edit(" + element.attributeValue("id") + ","
							+ element.attributeValue("status") + " ,this)")
					.setText(status);
		}
		request.setAttribute("table", table.asXML());
		request.setAttribute("dsid", dsid);
		return mapping.findForward("dictvalue");
	}
}