/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action;

import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTPrivilegeDAO;
import com.mingda.entity.SysTPrivilege;

/**
 * MyEclipse Struts Creation date: 04-18-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="submenu" path="/page/submenu.jsp"
 */
public class ReadSubMenuAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		/* 由主菜单传过来的menuid */
		String privilegeId = request.getParameter("privilegeId");
		Document doc = DocumentHelper.createDocument();
		// 设置XML编码
		doc.setXMLEncoding("GB18030");
		Element root = doc.addElement("root");
		Transaction tx = SessionFactory.getSession().beginTransaction();
		try {
			SysTPrivilegeDAO spd = new SysTPrivilegeDAO();
			/*root.addElement("td").addAttribute("class", "submenucap")
					.addAttribute("align", "left").setText(
							spd.findById(new Long(privilegeId)).getNav());*/
			List submenus = spd.findByParentprivilegeid(new Long(privilegeId));
			Iterator it = submenus.iterator();
			while (it.hasNext()) {
				Element td = root.addElement("td").addAttribute("class",
						"submenucap1").addAttribute("align", "center");
				td.addAttribute("width", "80px");
				SysTPrivilege sp = (SysTPrivilege) it.next();
				td.addElement("a").addAttribute("href", sp.getUrl())
						.addAttribute("target", sp.getTarget()).addAttribute("onclick", "writernav('"+sp.getNav()+"')").setText(
								sp.getDisplayname());
			}
			tx.commit();
		} catch (RuntimeException e) {
			tx.rollback();
			e.printStackTrace();
		} finally {
			SessionFactory.closeSession();
		}
		request.setAttribute("subMenu", doc);
		return mapping.findForward("submenu");
	}
}