/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.infovalidate;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.validation.GenerateValidation;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 09-20-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ValidateexecuteAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String termId = request.getParameter("termId");
		HttpSession hsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) hsession
				.getAttribute("employee");
		String organno = employee.getSysTOrganization().getOrganizationId();
		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		try {
			GenerateValidation gv = new GenerateValidation();
			gv.insertValidations(new Long(organno), new Long(termId));
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
		} finally {
			session.close();
		}

		ActionForward forward = new ActionForward();
		forward.setPath("/page/infovalidate/infovalidatequery.do?valtype=" + termId);
		return forward;
	}
}