/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.organ;

import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.dao.BizTOptreviewpersonDAO;
import com.mingda.entity.BizTOptreviewperson;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 04-17-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class OperpersonsaveAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String optreviewpersonId = request.getParameter("optreviewpersonId");
		String name = request.getParameter("name");
		String sex = request.getParameter("sex");
		String face = request.getParameter("face");
		String officephone = request.getParameter("officephone");
		String officename = request.getParameter("officename");
		String post = request.getParameter("post");
		String address = request.getParameter("address");
		String status = "1";

		HttpSession httpsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) httpsession
				.getAttribute("employee");

		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();

		BizTOptreviewpersonDAO bizTOptreviewpersonDAO = new BizTOptreviewpersonDAO();
		BizTOptreviewperson bizTOptreviewperson = new BizTOptreviewperson();

		try {
			if (null == optreviewpersonId || "".equals(optreviewpersonId)) {
			} else {
				bizTOptreviewperson = bizTOptreviewpersonDAO
						.findById(new Long(optreviewpersonId));
				bizTOptreviewperson.setOptreviewpersonId(new Long(optreviewpersonId));
			}
			bizTOptreviewperson.setAddress(address);
			bizTOptreviewperson.setFace(new BigDecimal(face));
			bizTOptreviewperson.setName(name);
			bizTOptreviewperson.setOfficename(officename);
			bizTOptreviewperson.setOfficephone(officephone);
			bizTOptreviewperson.setPost(post);
			bizTOptreviewperson.setOrganizationId(employee
					.getSysTOrganization().getOrganizationId());
			bizTOptreviewperson.setSex(new BigDecimal(sex));
			bizTOptreviewperson.setStatus(status);

			bizTOptreviewpersonDAO.save(bizTOptreviewperson);

			tx.commit();

		} catch (Exception ex) {
			ex.printStackTrace();
			tx.rollback();
		} finally {
			session.close();
		}

		ActionForward forward = new ActionForward(
				"/page/organ/operpersoninit.do");
		
		try {
			PrintWriter out = response.getWriter();
			out.println("<br><p style=\"font-size:12px\">");
			out.println("±£´æ³É¹¦");
			out.println("</p>");
			out.flush();
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		}

		return null;
	}
}