/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.organ;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.organ.OrganEditHandle;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 12-06-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="organundoedit"
 *                        path="/page/organ/organundoedit.jsp"
 */
public class OrganeditundoinitAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Session session = SessionFactory.getSession();
		HttpSession hsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) hsession
				.getAttribute("employee");
		String localorgid = employee.getSysTOrganization().getOrganizationId();
		OrganEditHandle o = new OrganEditHandle();
		Transaction tx = session.beginTransaction();
		try {
			request.setAttribute("olist", o.getOldOrgan(localorgid));
			request.setAttribute("nlist", o.getNewOrgan(localorgid));
			request.setAttribute("button", "0");
			tx.commit();
		} catch (RuntimeException e) {
			e.printStackTrace();
		} finally {
			session.close();
		}
		return mapping.findForward("organeditcommit");
	}
}