/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.organ;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTOrganizationDAO;
import com.mingda.entity.SysTOrganization;

/**
 * MyEclipse Struts Creation date: 12-01-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class OrgangetchildsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String orgid = request.getParameter("orgid");
		String htmlstr = "";
		if (null == orgid || "".equals(orgid)) {

		} else {
			String val = "&nbsp;";
			for (int i = 0; i < orgid.length() - 2; i++) {
				val += "&nbsp;";
			}

			Session session = SessionFactory.getSession();
			SysTOrganizationDAO organdao = new SysTOrganizationDAO();
			List<SysTOrganization> list = organdao.findByParentorgid(orgid);

			for (SysTOrganization sysTOrganization : list) {
				String temp = "";
				if (5 == sysTOrganization.getDepth().longValue()) {
					temp = "<input onclick=\"checkorg(this)\" name=\"checkid\" type=\"checkbox\" value=\""
							+ sysTOrganization.getOrganizationId() + "\"/>";
				}
				htmlstr += "<div  style=\"height: 16px;cursor:hand\"  id=\"p"
						+ sysTOrganization.getOrganizationId() + "\" >";
				htmlstr += val
						+ temp
						+ "<span style=\"height: 16px;cursor:hand\" onclick=\"expand("
						+ sysTOrganization.getOrganizationId() + ")\">"
						+ sysTOrganization.getOrgname() + "</span>";
				htmlstr += "</div><div style=\"display:none\" id =\"c"
						+ sysTOrganization.getOrganizationId() + "\"></div>";
			}
			session.close();
		}
		response.setCharacterEncoding("GB18030");
		try {
			PrintWriter out = response.getWriter();
			if ("".equals(htmlstr)) {
				htmlstr = "0";
			}
			out.println(htmlstr);
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
}