/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.organ;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTOrganizationDAO;
import com.mingda.entity.SysTEmployee;
import com.mingda.entity.SysTOrganization;

/**
 * MyEclipse Struts Creation date: 12-02-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class OrganfindbylevelAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		HttpSession hsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) hsession
				.getAttribute("employee");

		String orgid = employee.getSysTOrganization().getOrganizationId();
		long organdepth = employee.getSysTOrganization().getDepth().longValue();
		String organname = "";

		switch (orgid.length() + 2) {
		case 2:
			organname = "省级";
			break;
		case 4:
			organname = "市（州）级";
			break;
		case 6:
			organname = "县(市、区)";
			break;
		case 8:
			organname = "乡（镇、街道）";
			break;
		case 10:
			organname = "村(屯、社区)";
			break;
		default:
			;
		}
		String title = "";
		if (5 == organdepth) {
			title = "name=\"corg\"";
		} else {
			title = "name=\"porg" + organdepth
					+ "\"  onchange=\"findchilds(this)\"";
		}
		organdepth =organdepth+1;
		String htmlstr = "<span id =\"c" + organdepth+ "\" >" +organname + ":<select  " + title + " ><option value=\"\">未选择...</option>";
		Session session = SessionFactory.getSession();
		// String orglevel = request.getParameter("orglevel");
		SysTOrganizationDAO orgdao = new SysTOrganizationDAO();
		List<SysTOrganization> list = orgdao.findByParentorgid(orgid);
		for (SysTOrganization sysTOrganization : list) {
			htmlstr = htmlstr + "<option value=\""
					+ sysTOrganization.getOrganizationId() + "\">"
					+ sysTOrganization.getOrgname() + "</option>";
		}
		htmlstr += "</select></span>";
		session.close();

		response.setCharacterEncoding("GB18030");
		try {
			PrintWriter out = response.getWriter();
			out.println(htmlstr);
			out.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
}