/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.organ;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTOrganizationDAO;
import com.mingda.entity.SysTOrganization;

/**
 * MyEclipse Struts Creation date: 12-05-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class OrganstopAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String organizationId = request.getParameter("organizationId");

		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		SysTOrganizationDAO organdao = new SysTOrganizationDAO();
		SysTOrganization organ = organdao.findById(organizationId);
		if ("1".equals(organ.getStatus())) {
			organ.setStatus("0");
		} else {
			organ.setStatus("1");
		}
		organdao.save(organ);
		tx.commit();
		session.close();
		ActionForward forward =new ActionForward("/page/organ/organstopinit.do?organizationId="+organizationId);
		return forward;
	}
}