/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system;

import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTOrganizationDAO;
import com.mingda.entity.SysTOrganization;

/**
 * MyEclipse Struts Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="employee" path="/page/system/employee.jsp"
 */
public class EmployeelistAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String organizationId = request.getParameter("organizationId");
		SysTOrganizationDAO sysTOrganizationDAO = new SysTOrganizationDAO();
		SysTOrganization org = sysTOrganizationDAO.findById(organizationId);
		Set list = org.getSysTEmployees();
		request.setAttribute("organname", org.getFullname());
		request.setAttribute("organizationId", org.getOrganizationId());
		request.setAttribute("list", list);
		return mapping.findForward("employee");
	}
}