/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Transaction;

import com.mingda.dao.SysTEmployeeDAO;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 08-18-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ResetpwdAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String empid = request.getParameter("empid");
		SysTEmployeeDAO sysTEmployeeDAO = new SysTEmployeeDAO();
		Transaction tx = sysTEmployeeDAO.getSession().beginTransaction();
		try {
			SysTEmployee sysTEmployee = sysTEmployeeDAO
					.findById(new Long(empid));
			sysTEmployee.setPassword("1234567");
			sysTEmployeeDAO.save(sysTEmployee);
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
		}
		return null;
	}
}