/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.system;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;
import com.mingda.dao.SysTRoleDAO;

/**
 * MyEclipse Struts Creation date: 08-21-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class RolelistAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String roleId = request.getParameter("roleId");
		if (null == roleId || "".equals(roleId)) {
		} else {
			request.setAttribute("cid", roleId);
		}
		Session session = SessionFactory.getSession();
		SysTRoleDAO sysTRoleDAO = new SysTRoleDAO();
		List list = sysTRoleDAO.findAll();

		request.setAttribute("roles", list);
		return mapping.findForward("role");
	}
}