/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.implemention;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 11-20-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class BillctreatfilepriviewAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unused")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String monthid = request.getParameter("monthid");
		String defineid = request.getParameter("defineid");
		String[] organids = request.getParameterValues("organid");
		String[] orgnames = request.getParameterValues("orgname");
		HttpSession hsession = request.getSession();
		if (null == organids || organids.length == 0) {
			SysTEmployee employee = (SysTEmployee) hsession
					.getAttribute("employee");
			orgnames = new String[1];
			organids = new String[1];
			organids[0] = employee.getSysTOrganization().getOrganizationId();
			orgnames[0] = employee.getSysTOrganization().getOrgname();
		}
		// 读取文件生成列表
		String[] filetypenames = { "变更户主停发", "迁移和新开折", "续存" };
		String[] types = { "1", "2", "3" };//文件定义
		// 定义格式文件类型列表
		Object[] dfiles = new Object[8];// 1.换户主停发 2.迁移和新开折3.续存4.机构名称
		List<Object[]> filelist = new ArrayList<Object[]>();

		for (int i = 0; i < organids.length; i++) {
			dfiles = new Object[5];
			dfiles[0] = filetypenames[0];
			dfiles[1] = filetypenames[1];
			dfiles[2] = filetypenames[2];
			dfiles[3] = orgnames[i].toString();
			dfiles[4] = organids[i].toString();
			filelist.add(dfiles);
		}
		request.setAttribute("monthid", monthid);
		request.setAttribute("defineid", defineid);
		request.setAttribute("filelist", filelist);
		return mapping.findForward("billcreatefilepriview");
	}
}