/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.implemention;

import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.Globals;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.dictionary.DictionaryHandle;
import com.mingda.dao.BizTOptaccDAO;
import com.mingda.dao.ImplTMonthDAO;
import com.mingda.entity.BizTOptacc;
import com.mingda.entity.ImplTMonth;
import com.mingda.entity.SysTDictionary;
import com.mingda.entity.SysTEmployee;

public class BillcreateinitAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		HttpSession httpsession = request.getSession();
		SysTEmployee employee = (SysTEmployee) httpsession
				.getAttribute("employee");
		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		try {
			tx.begin();
			BizTOptaccDAO bizTOptaccDAO = new BizTOptaccDAO();
			List<BizTOptacc> list = bizTOptaccDAO.getOverBatch(employee
					.getSysTOrganization().getOrganizationId());

			ImplTMonthDAO monthdao = new ImplTMonthDAO();
			List<ImplTMonth> monthdonelist = monthdao.getMonthDoneList(employee
					.getSysTOrganization().getOrganizationId());

			Document dictionary = (Document) this.servlet.getServletContext()
					.getAttribute("dictionary");
			DictionaryHandle dh = new DictionaryHandle();
			List<SysTDictionary> implmonths = dh.getDictsortToArrayList(
					dictionary, "309");

			for (Iterator<SysTDictionary> it = implmonths.iterator(); it
					.hasNext();) {
				SysTDictionary sysTDictionary = it.next();
				for (ImplTMonth month : monthdonelist) {
					String monthnameall = month.getMonname().substring(0, 4)
							+ "Äê" + month.getMonname().substring(4, 6) + "ÔÂ";
					if (monthnameall.equals(sysTDictionary.getItem())) {
					}
				}
			}
			request.setAttribute("months", implmonths);
			request.setAttribute("monthdonelist", monthdonelist);
			request.setAttribute("overlist", list);
			this.saveToken(request);
			Globals s = new Globals();
			s.hashCode();
			tx.commit();
		} catch (RuntimeException re) {
			tx.rollback();
			re.printStackTrace();
		} finally {
			SessionFactory.closeSession();
		}
		return mapping.findForward("billcreate");
	}
}