/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.implemention;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mingda.common.SessionFactory;
import com.mingda.common.implemention.BillmonthHandle;
import com.mingda.dao.SysTOrganizationDAO;
import com.mingda.entity.ImplTMonth;
import com.mingda.entity.SysTEmployee;

/**
 * MyEclipse Struts Creation date: 12-05-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="implementionmonthquery"
 *                        path="/page/implemention/implementionmonthquery.jsp"
 */
public class ImplementionmonthqueryinitAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		HttpSession httpsession = request.getSession();

		Session session = SessionFactory.getSession();
		Transaction tx = session.beginTransaction();

		SysTEmployee employee = (SysTEmployee) httpsession
				.getAttribute("employee");

		BillmonthHandle billmonthhandle = new BillmonthHandle();

		try {

			String orgid = employee.getSysTOrganization().getOrganizationId();
			List<ImplTMonth> list = billmonthhandle.findUsedMonth(orgid);

			SysTOrganizationDAO organdao = new SysTOrganizationDAO();

			request.setAttribute("orglist", organdao.findByParentId(orgid));
			request.setAttribute("monlist", list);
			tx.commit();

		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			session.close();
		}
		return mapping.findForward("implementionmonthquery");
	}
}