/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.implemention;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;

@SuppressWarnings("all")
public class InterfacedefineviewAction extends Action {
	static Logger log = Logger.getLogger(InterfacedefineviewAction.class);

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id = request.getParameter("id");
		log.debug(id);
		Document xmldoc = null;
		try {
			if (!"add".equals(id)) {
				Session session = SessionFactory.getSession();
				ResultSet rs = null;
				PreparedStatement ps = null;
				String sql = "select impltinter0_.TEMPLATE.getStringVal() as template "
						+ "  from SALVATION.IMPL_T_INTERFACEDEFINE impltinter0_"
						+ " where impltinter0_.INTERFACEDEFINE_ID = '"
						+ id
						+ "'";
				Connection con = session.connection();
				ps = con.prepareStatement(sql);
				rs = ps.executeQuery();
				String template = null;
				if (rs.next()) {
					template = rs.getString("template");
				}
				log.debug(template.toString());
				xmldoc = DocumentHelper.parseText(template.toString());
				ps.close();
				rs.close();
				session.close();
			}
			response.setContentType("text/html");
			response.setCharacterEncoding("GB18030");
			PrintWriter out = response.getWriter();
			if (null == xmldoc) {
				out.println("0");
			} else {
				out.println(xmldoc.asXML());
			}
		} catch (DocumentException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}
}