/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.policy.approvalidea2;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.common.myjdbc.ConnectionManager;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PolicyideapageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// 获取action
		String action = request.getParameter("action");		
		//log.debug(action);
		//
		response.setContentType("text/html; charset=UTF-8");
		
		try {
			request.setCharacterEncoding("UTF-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		//
		try {
			PrintWriter out = response.getWriter();
			//
			if (action.equals("getCheckIdeaSelect")) {
				String sname = request.getParameter("sname");
				String stabid = request.getParameter("stabid");
				String sonecheck = request.getParameter("sonecheck");
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.getCheckIdeaSelect(sname, stabid,sonecheck));
			} else if (action.equals("getRequestTypeCheckBox")) {
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.getRequestTypeCheckBox());
			}  else if (action.equals("getRequestPersonCheckBox")) {
				String deptid = request.getParameter("deptid");
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.getRequestPersonCheckBox(deptid));
			}else if (action.equals("updateMoneyFromOptID")) {
				String joptid = request.getParameter("joptid");
				String jmoney = request.getParameter("jmoney");
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.updateMoneyFromOptID(joptid,jmoney));
			} else if (action.equals("getIdeaResultForXml")) {
				String jonecheck = request.getParameter("jonecheck");
				String jendcheck = request.getParameter("jendcheck");
				String jpid = request.getParameter("jpid");
				String jfmids = request.getParameter("jfmids");
				String jaccmode = request.getParameter("jaccmode");
				HashMap hashmap = new HashMap();
				hashmap.put("jonecheck", jonecheck);
				hashmap.put("jendcheck", jendcheck);
				hashmap.put("jpid", jpid);
				hashmap.put("jfmids", jfmids);
				hashmap.put("jaccmode", jaccmode);
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.getIdeaResultForXml(hashmap));
			}else if (action.equals("addCheckIdea")) {
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				//
				String jtabid = request.getParameter("jtabid");
				String jpid = request.getParameter("jpid");
				String jfmids = request.getParameter("jfmids");
				String jonecheck = request.getParameter("jonecheck");
				String jendcheck = request.getParameter("jendcheck");
				String jreport = request.getParameter("jreport");
				String jbegdt = request.getParameter("jbegdt");
				String jenddt = request.getParameter("jenddt");
				String jresult = request.getParameter("jresult");
				String jcheckdt = request.getParameter("jcheckdt");
				String jdesc = request.getParameter("jdesc");
				String jmanall = request.getParameter("jmanall");
				String jmanok = request.getParameter("jmanok");
				String jmandel = request.getParameter("jmandel");
				String jmannot = request.getParameter("jmannot");
				String jmanids = request.getParameter("jmanids");
				//
				//===========================================转码===================
				jdesc = URLDecoder.decode(jdesc, "UTF-8");
				//===========================================转码===================
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	//
            	hashmap.put("jtabid", jtabid);
				hashmap.put("jpid", jpid);
				hashmap.put("jfmids", jfmids);
				hashmap.put("jonecheck", jonecheck);
				hashmap.put("jendcheck", jendcheck);
				hashmap.put("jreport", jreport);
				hashmap.put("jbegdt", jbegdt);
				hashmap.put("jenddt", jenddt);
				hashmap.put("jresult", jresult);
				hashmap.put("jcheckdt", jcheckdt);
				hashmap.put("jdesc", jdesc);
				hashmap.put("jmanall", jmanall);
				hashmap.put("jmanok", jmanok);
				hashmap.put("jmandel", jmandel);
				hashmap.put("jmannot", jmannot);
				hashmap.put("jmanids", jmanids);
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.validationCheckIdea("addCheckIdea",hashmap));
			}else if (action.equals("updateCheckIdea")) {
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				//
				String jtabid = request.getParameter("jtabid");
				String jpid = request.getParameter("jpid");
				String jfmids = request.getParameter("jfmids");
				String jonecheck = request.getParameter("jonecheck");
				String jendcheck = request.getParameter("jendcheck");
				String jreport = request.getParameter("jreport");
				String jbegdt = request.getParameter("jbegdt");
				String jenddt = request.getParameter("jenddt");
				String jresult = request.getParameter("jresult");
				String jcheckdt = request.getParameter("jcheckdt");
				//
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	//
            	hashmap.put("jtabid", jtabid);
				hashmap.put("jpid", jpid);
				hashmap.put("jfmids", jfmids);
				hashmap.put("jonecheck", jonecheck);
				hashmap.put("jendcheck", jendcheck);
				hashmap.put("jreport", jreport);
				hashmap.put("jbegdt", jbegdt);
				hashmap.put("jenddt", jenddt);
				hashmap.put("jresult", jresult);
				hashmap.put("jcheckdt", jcheckdt);
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.validationCheckIdea("updateCheckIdea",hashmap));
			}else if (action.equals("allCheckIdea")) {
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				//
				String jtabid = request.getParameter("jtabid");
				String jpid = request.getParameter("jpid");
				String jallsql = request.getParameter("jallsql");
				String jonecheck = request.getParameter("jonecheck");
				String jendcheck = request.getParameter("jendcheck");
				String jreport = request.getParameter("jreport");
				String jresult = request.getParameter("jresult");
				String jcheckdt = request.getParameter("jcheckdt");
				//===========================================转码===================
				jallsql = URLDecoder.decode(jallsql, "UTF-8");
				//===========================================转码===================
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	//
            	hashmap.put("jtabid", jtabid);
				hashmap.put("jpid", jpid);
				hashmap.put("jallsql", jallsql);
				hashmap.put("jonecheck", jonecheck);
				hashmap.put("jendcheck", jendcheck);
				hashmap.put("jreport", jreport);
				hashmap.put("jresult", jresult);
				hashmap.put("jcheckdt", jcheckdt);
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.validationCheckIdea("allCheckIdea",hashmap));
			}else if (action.equals("moneyCheckIdea")) {
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				//
				String jtabid = request.getParameter("jtabid");
				String jpid = request.getParameter("jpid");
				String jfmids = request.getParameter("jfmids");
				String jonecheck = request.getParameter("jonecheck");
				String jendcheck = request.getParameter("jendcheck");
				String jreport = request.getParameter("jreport");
				String jresult = request.getParameter("jresult");
				String jcheckdt = request.getParameter("jcheckdt");
				//
				String jmoney = request.getParameter("jmoney");
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	//
            	hashmap.put("jtabid", jtabid);
				hashmap.put("jpid", jpid);
				hashmap.put("jfmids", jfmids);
				hashmap.put("jonecheck", jonecheck);
				hashmap.put("jendcheck", jendcheck);
				hashmap.put("jreport", jreport);
				hashmap.put("jresult", jresult);
				hashmap.put("jcheckdt", jcheckdt);
				hashmap.put("jmoney", jmoney);
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.validationCheckIdea("moneyCheckIdea",hashmap));
			}	else if (action.equals("allMoneyCheckIdea")) {
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				//
				String jtabid = request.getParameter("jtabid");
				String jpid = request.getParameter("jpid");
				String jallsql = request.getParameter("jallsql");
				String jonecheck = request.getParameter("jonecheck");
				String jendcheck = request.getParameter("jendcheck");
				String jreport = request.getParameter("jreport");
				String jresult = request.getParameter("jresult");
				String jcheckdt = request.getParameter("jcheckdt");
				//
				String jmoney = request.getParameter("jmoney");
				//===========================================转码===================
				jallsql = URLDecoder.decode(jallsql, "UTF-8");
				//===========================================转码===================
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	//
            	hashmap.put("jtabid", jtabid);
				hashmap.put("jpid", jpid);
				hashmap.put("jallsql", jallsql);
				hashmap.put("jonecheck", jonecheck);
				hashmap.put("jendcheck", jendcheck);
				hashmap.put("jreport", jreport);
				hashmap.put("jresult", jresult);
				hashmap.put("jcheckdt", jcheckdt);
				hashmap.put("jmoney", jmoney);
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.validationCheckIdea("allMoneyCheckIdea",hashmap));
			}	else if (action.equals("getIdeaFlowForXml")) {
				String jempid = request.getParameter("jempid");
				String jdeptid = request.getParameter("jdeptid");
				String jdepth = request.getParameter("jdepth");
				//
				String jpid = request.getParameter("jpid");
				String jfmids = request.getParameter("jfmids");
				//
				HashMap hashmap = new HashMap();
				//
            	hashmap.put("jempid", jempid);
            	hashmap.put("jdeptid", jdeptid);
            	hashmap.put("jdepth", jdepth);
            	//
            	hashmap.put("jpid", jpid);
            	hashmap.put("jfmids", jfmids);				
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.getIdeaFlowForXml(hashmap));
			}	else if (action.equals("getIdeaFlowDesrForXml")) {
				String jpid = request.getParameter("jpid");
				String joptdepth = request.getParameter("joptdepth");
				String joptid = request.getParameter("joptid");
				//
				HashMap hashmap = new HashMap();
				//
				hashmap.put("jpid", jpid);
            	hashmap.put("joptdepth", joptdepth);
            	hashmap.put("joptid", joptid);			
				Policyideapage policyideapage = new Policyideapage();
				out.print(policyideapage.getIdeaFlowDesrForXml(hashmap));
			}
		} catch (IOException e) {
			e.printStackTrace();
		}finally{
			ConnectionManager.closeQuietly();
		}
		return null;
	}
}