/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.paperprint;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mingda.common.SessionFactory;
import com.mingda.common.paperprint.PaperPrint;
import com.mingda.entity.ImplTPaperrecord;

/**
 * MyEclipse Struts Creation date: 01-21-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class PapervaliqueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String papertype = request.getParameter("papertype");
		String valicode = request.getParameter("valicode");

		PaperPrint paperprint = new PaperPrint();
		try {
			
			ImplTPaperrecord implTPaperrecord = paperprint.validatePaper(
					papertype, valicode);

			if (null != implTPaperrecord) {
				String fid = implTPaperrecord.getFamilyId().toString();
				Object[] objs = paperprint.getFamilyInfo(fid);
				request.setAttribute("mastername", objs[1].toString());
				request.setAttribute("familyno", objs[0].toString());
				request.setAttribute("papername" ,implTPaperrecord.getImplTPapertype().getPapername());
				request.setAttribute("flag" ,implTPaperrecord.getFlag());
				request.setAttribute("result","ok");
			}else{
				request.setAttribute("result", "没有与验证码匹配的证件信息 ");
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			SessionFactory.closeSession();
		}
		return mapping.findForward("papervaliquery");
	}
}