/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingda.action.paperprint;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.mingda.common.SessionFactory;
import com.mingda.common.paperprint.PaperPrint;
import com.mingda.entity.BizTFamilystatus;
import com.mingda.entity.ImplTPaperinfo1;

/**
 * MyEclipse Struts Creation date: 01-15-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class PrintpaperpreivewAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String ptid = request.getParameter("ptid");
		String fid = request.getParameter("fid");
		PaperPrint paperprint = new PaperPrint();
		Session session = SessionFactory.getSession();
		try {
			BizTFamilystatus bizTFamilystatus = paperprint.getFamilyStatus(fid,
					ptid);
			String mastername = bizTFamilystatus.getInfoTFamily()
					.getMastername();
			String familyno = bizTFamilystatus.getInfoTFamily().getFamilyno();
			request.setAttribute("mastername", mastername);
			request.setAttribute("familyno", familyno);
			request.setAttribute("ptid", ptid);
			request.setAttribute("fid", fid);
			request.setAttribute("bizTFamilystatus", bizTFamilystatus);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			session.close();
		}
		return mapping.findForward("paperprintpreiview");
	}
}